
package com.lm.bos.crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceImpl", targetNamespace = "http://impl.service.crm.bos.lm.com/")
public interface CustomerServiceImpl {


    /**
     * 
     * @param telephone
     * @return
     *     returns com.lm.bos.crm.service.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByTelephoneResponse")
    public Customer findByTelephone(
            @WebParam(name = "telephone", targetNamespace = "")
                    String telephone);

    /**
     * 
     * @return
     *     returns java.util.List<com.lm.bos.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param fixedAreaId
     * @return
     *     returns java.util.List<com.lm.bos.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
            @WebParam(name = "fixedAreaId", targetNamespace = "")
                    String fixedAreaId);

    /**
     * 
     * @param telephone
     */
    @WebMethod
    @RequestWrapper(localName = "activeMail", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.ActiveMail")
    @ResponseWrapper(localName = "activeMailResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.ActiveMailResponse")
    public void activeMail(
            @WebParam(name = "telephone", targetNamespace = "")
                    String telephone);

    /**
     * 
     * @return
     *     returns java.util.List<com.lm.bos.crm.service.impl.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param fixedAreaId
     * @param customerIds
     */
    @WebMethod
    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.AssignCustomers2FixedArea")
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.AssignCustomers2FixedAreaResponse")
    public void assignCustomers2FixedArea(
            @WebParam(name = "fixedAreaId", targetNamespace = "")
                    String fixedAreaId,
            @WebParam(name = "customerIds", targetNamespace = "")
                    List<Integer> customerIds);

    /**
     * 
     * @param password
     * @param telephone
     * @return
     *     returns com.lm.bos.crm.service.impl.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.LoginResponse")
    public Customer login(
            @WebParam(name = "telephone", targetNamespace = "")
                    String telephone,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param customer
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.RegistResponse")
    public void regist(
            @WebParam(name = "customer", targetNamespace = "")
                    Customer customer);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFixedAreaIdByAddress", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindFixedAreaIdByAddress")
    @ResponseWrapper(localName = "findFixedAreaIdByAddressResponse", targetNamespace = "http://impl.service.crm.bos.lm.com/", className = "com.lm.bos.crm.service.impl.FindFixedAreaIdByAddressResponse")
    public String findFixedAreaIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
